/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "STM32F446xx.h"

#define GPIOAEN (1U<<0)		//6.3.10 RCC AHB1 peripheral clock enable register (RCC_AHB1ENR)
							//Bit 0 GPIOAEN: IO port A clock enable
							//1: IO port A clock enabled
//#define PIN5				(1U<<5) //0b 0000 0000 0000 0000 0010 0000 0000 0000
//#define LED_PIN				PIN5

//#define GPIOA_OD_R			(*(volatile unsigned int *)(GPIOG_BASE + OD_R_OFFSET))

int main(void)
{
	//clock to gpioa
	RCC->AHB1ENR |= GPIOAEN; //6.3.10 RCC AHB1 peripheral clock enable register (RCC_AHB1ENR)

	//SET PA5 to alternate function mode
	//7.4.1 GPIO port mode register (GPIOx_MODER) (x = A..H)
	//01: General porpose output
	GPIOA->MODER |=   (1U<<10); // set to 1
	GPIOA->MODER &=  ~(1U<<11); // set to 0

	while(1)
	{
		GPIO_ODR_OD5_A
		//GPIOA_ODR = (1U<<5);
		for (int var = 0; var < 500000; ++var)
		{

		}

	}
}
