/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * PORT:G
 * PIN: 13
 *
 *
 *
 ******************************************************************************
 */

#define PERIPH_BASE  		(0x40000000UL)
#define AHB1PERIPH_OFFSET  	(0x00020000UL)
#define AHB1PERIPH_BASE		PERIPH_BASE + AHB1PERIPH_OFFSET
#define GPIOG_OFFSET		(0X1800UL)
#define GPIOG_BASE			AHB1PERIPH_BASE + GPIOG_OFFSET
#define RCC_OFFSET			(0X3800UL)
#define RCC_BASE            AHB1PERIPH_BASE + RCC_OFFSET

#define AHB1EN_R_OFFSET		(0x30UL) //revisar video 6 3 ultimos minutos udemy)
#define RCC_AHB1EN_R		(*(volatile unsigned int *)(RCC_BASE + AHB1EN_R_OFFSET))//revisar

#define MODE_R_OFFSET		(0x00UL)
#define GPIOG_MODE_R		(*(volatile unsigned int *)(GPIOG_BASE + MODE_R_OFFSET))

#define OD_R_OFFSET			(0x14UL)
#define GPIOG_OD_R			(*(volatile unsigned int *)(GPIOG_BASE + OD_R_OFFSET))
//PG13

#define GPIOGEN				(1U<<6)//entrega ciclo reloj al puerto


#define PIN13				(1U<<13) //0b 0000 0000 0000 0000 0010 0000 0000 0000
#define LED_PIN				PIN13

//(1U<<10)    Set bit 10 to 1
//&=~(1U<<11) Set bit 11 to 0

int main(void){

	//1 Enable clock access to GOIOGEN
	RCC_AHB1EN_R |= GPIOGEN;
	//2 Set PG13 as output
	GPIOG_MODE_R |= (1U<<26); //Set bit 10 to 1
	GPIOG_MODE_R &= ~(1U<<27); //Set bit 11 to 0
	while(1){
		GPIOG_OD_R ^= LED_PIN;
		for (int var = 0; var < 500000; ++var) {

		}
	}
}


